version: '3.4'

services:
  fastapi:
    build:
      context: .
      target: fastAPI
    depends_on:
      - redis
    ports:
      - "8001"
    env_file:
      - .env
    networks:
      - my_network

  fastapi_nginx:
    image: nginx:latest
    volumes:
      - ./src/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./src/nginx_config:/etc/nginx/conf.d:ro
    depends_on:
      - fastapi
    ports:
      - "81:81"
    networks:
      - my_network

  redis:
    image: redis:latest    
    ports:
      - "6379"
    networks:
      - my_network

  tests:
    build:
      context: .
      target: tests
    container_name: tests
    depends_on:
      - fastapi_nginx
    env_file:
      - .env
    networks:
      - my_network

networks:
  my_network:
    external: True
